### ISSUE TITLE
请问Custome怎么使用，想加入版权信息

### ISSUE THREAD

**Issue by yyhclimacool** [leslievan/semi-utils#76]

**Comment by yyhclimacool** [comment]
知道了，配置value字段即可：
```yaml
    right_bottom:
      color: '#757575'
      is_bold: false
      name: Custom
      value: Photo by XXX
```
