### ISSUE TITLE
use_equivalent_focal_length: true 等效焦距好像没有生效

### ISSUE THREAD

**Issue by CoolOilHero** [leslievan/semi-utils#90]
如题，尼康Z30，180mm，等效270mm，输出图片还是180mm
use_equivalent_focal_length: true 我只改了这一个参数
![2024-03-17_152059](https://github.com/leslievan/semi-utils/assets/53138900/365fc5c6-2996-45d0-8243-99b1f01ab6fd)

```
base:
  alternative_bold_font: ./fonts/Roboto-Medium.ttf
  alternative_font: ./fonts/Roboto-Regular.ttf
  bold_font: ./fonts/AlibabaPuHuiTi-2-85-Bold.otf
  bold_font_size: 1
  font: ./fonts/AlibabaPuHuiTi-2-45-Light.otf
  font_size: 1
  input_dir: ./input
  output_dir: ./output
  quality: 100
global:
  focal_length:
    use_equivalent_focal_length: true
  padding_with_original_ratio:
    enable: false
  shadow:
    enable: false
  white_margin:
    enable: true
    width: 3
```

180mm的半画幅焦距，等效焦距应该是270mm吧
